#!/bin/bash

cp .bashrc ~;
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
/bin/bash -c "$(curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)"
git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest

export PATH="$PATH:$(go env GOPATH)/bin"
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4

source ~/.bashrc;
brew install bufbuild/buf/buf
cp .vimrc ~;
cp -r .vim ~;
cp .gitconfig ~;
sudo apt-get install libterm-readline-perl-perl;
sudo apt-get install jq;

touch ~/.ssh/config
echo "Host github.com" > ~/.ssh/config
echo "IdentityFile ~/.ssh/junbon" >> ~/.ssh/config
chmod 644 ~/.ssh/config
ssh-add ~/.ssh/junbon

cd /home/git/regentmarkets;
for i in perl-Quant-Framework perl-Volatility-Seasonality perl-Finance-Asset perl-postgres-feeddb perl-LandingCompany perl-VolSurface-Empirical perl-Price-Calculator perl-Pricing-Engine-BlackScholes perl-Pricing-Engine-European-Digital-Slope perl-Pricing-Engine-TickExpiry perl-Pricing-Engine-Intraday-Forex-Base perl-Pricing-Engine-Digits perl-Pricing-Engine-Markup perl-Pricing-Engine-Lookback perl-Pricing-Engine-HighLow-Ticks perl-Pricing-Engine-Reset chef perl-Brands perl-Finance-Underlying perl-Finance-Contract perl-ExchangeRates perl-ExpiryQueue perl-Finance-Contract-Longcode perl-Pricing-Engine-Binomial-Step; do
    git clone git@github.com:regentmarkets/$i.git;
done;

cd /home/git/regentmarkets/bom-core;
git remote add junbon git@github.com:junbon-deriv/bom-core.git;
git fetch junbon;

for i in options-trading-contract options-trading-market-data options-trading-pricing-engine-blackscholes; do
cd /home/git/regentmarkets/;
git clone git@github.com:junbon-deriv/$i.git;
cd $i;
git remote add junbon git@github.com:junbon-deriv/$i.git;
git fetch junbon;
done;
